# Generated by Django 3.0.5 on 2020-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('PO', 'PURCHASING_OFFICER'), ('SO', 'SALE_OFFICER')], max_length=2),
        ),
    ]
