# Generated by Django 3.0.5 on 2020-04-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20200426_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='user_id',
        ),
    ]
