# Generated by Django 3.0.5 on 2020-04-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200426_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='account_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.Account'),
        ),
    ]
