# Generated by Django 3.0.5 on 2020-04-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200426_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='account_id',
            new_name='account',
        ),
    ]
