# Generated by Django 3.0.5 on 2020-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_auto_20200424_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
