# Generated by Django 3.0.5 on 2020-04-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200426_1933'),
        ('Manage', '0003_auto_20200424_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.Account'),
        ),
    ]
