# Generated by Django 3.0.5 on 2020-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_auto_20200427_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
